from . import _init_cscore

from ._logging import enableLogging

# autogenerated by 'robotpy-build create-imports cscore'
from ._cscore import (
    AxisCamera,
    CameraServer,
    CvSink,
    CvSource,
    HttpCamera,
    ImageSink,
    ImageSource,
    MjpegServer,
    RawEvent,
    UsbCamera,
    UsbCameraInfo,
    VideoCamera,
    VideoEvent,
    VideoListener,
    VideoMode,
    VideoProperty,
    VideoSink,
    VideoSource,
)

__all__ = [
    "AxisCamera",
    "CameraServer",
    "CvSink",
    "CvSource",
    "HttpCamera",
    "ImageSink",
    "ImageSource",
    "MjpegServer",
    "RawEvent",
    "UsbCamera",
    "UsbCameraInfo",
    "VideoCamera",
    "VideoEvent",
    "VideoListener",
    "VideoMode",
    "VideoProperty",
    "VideoSink",
    "VideoSource",
    "enableLogging",
]

try:
    from .version import __version__
except ImportError:
    __version__ = "master"
