---
name: CI
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v2
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist

  test:
    needs: [sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sdist
          path: dist

      - name: Add OpenCV 3.4 PPA
        if: matrix.os == 'ubuntu-18.04'
        run: sudo add-apt-repository -y ppa:~timsc/opencv-3.4
      - name: Use gcc-8
        uses: robotpy/build-actions/setup-cxx@v2022
        if: matrix.os == 'ubuntu-18.04'

      - name: Install dependencies
        run: |
          sudo apt-get install --no-install-recommends -y \
            libopencv-dev python3-opencv

      - name: Install Python setup requirements
        run: python3 -m pip install setuptools wheel pkgconfig

      - run: python3 -m pip install -v dist/*.tar.gz
      - run: python3 -m cscore --help

  cross-build:
    runs-on: ubuntu-latest
    needs: [sdist]
    container:
      image: robotpy/roborio-cross-ubuntu:2022.3

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: sdist
        path: dist
    - run: tar -xf dist/*.gz --strip-components=1
    - run: rm dist/*.gz
    - run: /build/venv/bin/cross-python -m pip install robotpy-wpiutil robotpy-opencv-core-dev distro
    - run: /build/venv/bin/cross-python setup.py bdist_wheel
    - uses: actions/upload-artifact@v2
      with:
        name: dist-roborio
        path: dist

  #
  # Publish wheels to robotpy site, pypi
  #

  publish-rpyrepo:
    runs-on: ubuntu-latest
    needs: [check, test, cross-build]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:

    #
    # RoboRIO wheel
    #

    - uses: actions/download-artifact@v2
      with:
        name: dist-roborio
        path: dist-roborio/

    - uses: robotpy/github-action-scp@atomic
      with:
        local: dist-roborio
        remote: public_html/2022/roborio
        host: narya.tortall.net
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        atomicPut: true

  publish-pypi:
    runs-on: ubuntu-latest
    needs: [check, test]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sdist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
