---
name: CI
on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Add OpenCV 3.4 PPA
        if: matrix.os == 'ubuntu-18.04'
        run: sudo add-apt-repository -y ppa:~timsc/opencv-3.4

      - name: Install dependencies
        run: |
          sudo apt-get install --no-install-recommends -y \
            libopencv-dev python3-opencv

      - name: Install Python setup requirements
        run: python3 -m pip install setuptools wheel pkgconfig

      - run: python3 setup.py sdist
      - run: python3 -m pip install dist/*.tar.gz
      - run: python3 -m cscore --help
  
  cross-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        - container: robotpy/roborio-cross-ubuntu:2021.3
          name:  roborio
        # - container: robotpy/raspbian-cross-ubuntu:2021.3
        #   name:  raspbian

    container:
      image: "${{ matrix.os.container }}"

    steps:
    - uses: actions/checkout@v2

    - uses: robotpy/build-actions/install-robotpy-build@v2021
      with:
        python: /build/venv/bin/cross-python
    - uses: robotpy/build-actions/install-build-deps@v2021
      with:
        python: /build/venv/bin/cross-python
        wheeldir: ${{ matrix.os.name }}
    - uses: robotpy/build-actions/build-wheel@v2021
      with:
        python: /build/venv/bin/cross-python

    - uses: actions/upload-artifact@v2
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      with:
        name: dist-${{ matrix.os.name }}
        path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [check, cross-build, test]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: python setup.py sdist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.0.0a0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
