---
name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  ci:
    uses: robotpy/build-actions/.github/workflows/package-ci.yml@v2024
    with:
      artifactory_repo_type: wpilib
      enable_sphinx_check: false
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      META_REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
      RTD_WEBHOOK: ${{ secrets.RTD_WEBHOOK }}
      WPI_ARTIFACTORY_USERNAME: ${{ secrets.WPI_ARTIFACTORY_USERNAME }}
      WPI_ARTIFACTORY_TOKEN: ${{ secrets.WPI_ARTIFACTORY_TOKEN }}
